<?php

namespace Kb\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PricingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingRepository extends EntityRepository
{
}
