<?php

namespace Kb\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeasionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasionRepository extends EntityRepository
{
}
