kb_core:
    resource: "@KbCoreBundle/Resources/config/routing.yml"
    prefix:   /

kb_core:
    resource: "@KbCarBundle/Resources/config/routing.yml"
    prefix:   /

kb_user:
    resource: "@KbUserBundle/Resources/config/routing.yml"
    prefix:   /

