services:
    kb_user.registration.form.type:
        class: Kb\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: kb_user_registration }