<?php

namespace Kb\CarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository {

    public function getCars($isActive = null) {

        $qb = $this->createQueryBuilder('c');
        if ($qb != null) {
            $qb->where('c.isActive = :isActive')
                    ->setParameter('isActive', $isActive);
        }
       return $qb->getQuery()
                ->getResult();
    }

}
