<?php

namespace Kb\CarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository {

    public function getCarsBySeasion(\DateTime $date, $isActive = null) {

        $qb = $this->createQueryBuilder('c');
        $qb->select('c.name,c.description,c.nbKm,p.amount,p.unitAmount');
        $qb->innerJoin('c.pricings', 'p','WITH','p.priceByDefault = 1')
                ->innerJoin('p.seasion', 's')
                ->where('s.dateStart <= :date and s.dateEnd >= :date')
                ->setParameter('date', $date);
         
        if ($qb != null) {
            $qb->andWhere('c.isActive = :isActive')
                    ->setParameter('isActive', $isActive);
        }
       return $qb->getQuery()
                ->getResult();
    }

}
