<?php

namespace Kb\CarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EngineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EngineRepository extends EntityRepository
{
}
